inherit_gem:
  rubocop-espago: sorbet.yml

Metrics/MethodLength:
  Enabled: false

Sorbet/RedundantExtendTSig:
  Enabled: false

Sorbet/HasSigil:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Sorbet/EnforceSignatures:
  Exclude:
    - 'bin/*'
    - 'test/**/*'

Sorbet/ForbidTUnsafe:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Sorbet/ForbidSig:
  Enabled: false

AllCops:
  TargetRubyVersion: 3.2.0
  EnabledByDefault: true
  Exclude:
    - 'bin/*'
    - 'sorbet/**/*'
